from bs4 import BeautifulSoup
import requests
from re import compile
from html import escape

url = 'https://www.rottentomatoes.com/m/deadpool_2'
url_imdb = 'https://www.imdb.com/title/tt5463162'

html_get = requests.get(url)
html_get.encoding = 'UTF-8'
html_get_imdb = requests.get(url_imdb)
html_get_imdb.encoding = 'UTF-8'

soup = BeautifulSoup(html_get.text, 'html.parser')
soup1 = BeautifulSoup(html_get_imdb.text, 'html.parser')

#get synopsis from rotten
def get_synopsis(html_soup): 
    synopsis = soup.find('div', id='movieSynopsis')
    return synopsis.text
#get movie name from rotten
def get_name(name):
    movie_name = soup.find('h1', class_= 'title hidden-xs')
    return movie_name.text
#get cast from imdb
def get_actors(actors):
    actors_name = soup1.find('h4' , class_='inline', text = 'Stars:')#finding category tag were actors are listed
    list_actors = actors_name.find_next_siblings('a', string=True, limit=3)
    actors_list = []
    for actors in list_actors:#iterate list generated by find_all
        actors_list.append(actors.text)#clean text and append new list
    return actors_list

def imdb_rating(url_adress):
    rating_div = soup1.find('div', class_='ratingValue')
    return rating_div.text

def rotten_rating(url_adress):
    rating_div = soup.find('div', class_='meter-value')
    get_rating = rating_div.find('span', class_ = 'superPageFontColor').get_text()
    return get_rating

def get_posters(url_adress):
    posters = soup.find('img', class_ = 'posterImage') #get only first poster. To be change after redesign
    return posters['src']

#print(get_posters(html_get))