from bs4 import BeautifulSoup
import requests
from re import compile

url = 'https://www.rottentomatoes.com/m/deadpool_2'
url_imdb = 'https://www.imdb.com/title/tt5463162'

html_get = requests.get(url)
html_get.encoding = 'UTF-8'
html_get_imdb = requests.get(url_imdb)
html_get_imdb.encoding = 'UTF-8'

soup = BeautifulSoup(html_get.text, 'html.parser')
soup1 = BeautifulSoup(html_get_imdb.text, 'html.parser')

#get synopsis from rotten
def get_synopsis(html_soup): 
    synopsis = soup.find('div', id='movieSynopsis')
    return synopsis.text
#get movie name from rotten
def get_name(name):
    movie_name = soup.find('h1', class_= 'title hidden-xs')
    return movie_name.text
#get cast from imdb
def get_actors(actors):
    actors_name = soup1.find('h4' , class_='inline', text = 'Stars:')#finding category tag were actors are listed
    print(actors_name.find_all_next(string=True, limit=3))
    actors_list = []
    print(actors_name)
  #for actors in actors_name:#iterate list generated by find_all
        #actor = actors.find_all('a')#extract <a>
        #for i in actor:#iterate list generate by find_all <a>
            #actors_list.append(i.text)#clean text and append new list
    #return actors_list

print(get_actors(url_imdb))